{% set name = "requests-aws4auth" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2950f6ff686b5a452a269076d990e4821d959b61cfac319c3d3c6daaa5db55ce

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - requests

test:
  imports:
    - requests_aws4auth

about:
  home: https://github.com/sam-washington/requests-aws4auth
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: AWS4 authentication for Requests
  doc_url: https://pypi.org/project/requests-aws4auth/
  dev_url: https://github.com/sam-washington/requests-aws4auth

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - mwilson8
